data_folder = "./data/"
file_name_length = 15
max_upload_size = 104857600
database_type = "postgresql"
database_connection_url = "host=localhost port=5432 user=postgres sslmode=disable"
web_port = "8080"
