data_folder = "/app/data/"
file_name_length = 15
max_upload_size = 104857600
database_type = "postgresql"
database_connection_url = "host=db port=5432 user=postgres password=123 database=imagehost sslmode=disable"
web_port = "80"
