// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package cmd

// Injectors from container.go:

func InitializeApplication() *Application {
	logger := setupLogging()
	templates := setupTemplates()
	config := initializeConfig(logger)
	database := prepareDB(logger, config)
	s3 := prepareStorage(logger, config)
	limiter := setupRatelimiting()
	cmdUninitializedApplication := &uninitializedApplication{
		Logger:      logger,
		Templates:   templates,
		config:      config,
		db:          database,
		s3client:    s3,
		RateLimiter: limiter,
	}
	application := addRouter(cmdUninitializedApplication)
	return application
}

// container.go:

type uninitializedApplication Application
