// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package cmd

// Injectors from container.go:

func InitializeApplication() *Application {
	config := initializeConfig()
	database := prepareDB(config)
	s3 := prepareStorage(config)
	limiter := setupRatelimiting(config)
	cmdUninitializedApplication := &uninitializedApplication{
		config:      config,
		db:          database,
		s3client:    s3,
		RateLimiter: limiter,
	}
	application := setupRouter(cmdUninitializedApplication, config)
	return application
}

// container.go:

type uninitializedApplication Application
